
#spring.http.encoding.charset=UTF-8
#spring.http.encoding.enabled=true
#spring.http.encoding.force=true
#spring.messages.encoding=UTF-8

#prod,dev
spring:
  profiles:
    active: dev

  #dubbo:
    #application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
     # name: provide
    #registry:                 #注册中心配置，用于配置连接注册中心相关信息。
      #address: zookeeper://122.114.251.98:2181
    #protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
      #name: dubbo
      #port: 20881
    #scan: cc.mrbird.job.service.impl  #服务暴露与发现消费所在的package
  thymeleaf:
    cache: false

  aop:
    proxy-target-class: true
  cache:
    type:
      redis

  #邮件所需freemarker
  freemarker:
      allowRequestOverride: false
      allowSessionOverride: false
      cache: true
      checkTemplateLocation: true
      contentType: text/html
      exposeRequestAttributes: false
      exposeSessionAttributes: false
      exposeSpringMacroHelpers: false
      suffix: .ftl
      templateEncoding: UTF-8
      templateLoaderPath: classpath:/templates/  #表示所有的模板文件都放在该目录下
      spring.freemarker.settings:
        locale: zh_CN
        date_format: yyyy-MM-dd
        time_format: HH:mm:ss
        datetime_format: yyyy-MM-dd HH:mm:ss

#spring boot admin配置
  #boot:
    #admin:
      #client:
        #url: http://localhost:8081/admin
        #username: mrbird
        #password: 123456
  #application:
    #name: niuhao
#admin
#management:
  #endpoints:
    #web:
      #exposure:
        #include: '*'
  #endpoint:
    #health:
      #show-details: ALWAYS

#其他配置
info:
  app:
    name: "niuhao"
    description: "spring boot&shiro NIUHAO广商管理系统"
    version: "2.0"
    spring-boot-version: "2.0.3.RELEASE"



mybatis:
  config-location: classpath:config/mybatis-config.xml
  # type-aliases扫描路径
  type-aliases-package: cc.mrbird.system.domain
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*/*.xml
  property:
    order: BEFORE

#mappers 多个接口时逗号隔开
mapper:
  mappers: cc.mrbird.common.config.MyMapper
  not-empty: false
  identity: MYSQL
  order: after

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#logging:
 # level:
  #  cc:
    #  mrbird:
    #    system:
      #    dao: debug


# niuhaoone 配置
niuhaoone:
  shiro:
    # shiro redis缓存时长，默认 1800 秒
    expireIn: 1800
    # session 超时时间，默认 1800000 毫秒
    sessionTimeout: 1800000
    # rememberMe cookie有效时长，默认 86400 秒，即一天
    cookieTimeout: 86400
    # 免认证的路径配置，如静态资源，druid监控页面，注册页面，验证码请求等
    anonUrl: /css/**,/js/**,/fonts/**,/img/**,/druid/**,/user/regist,/error/*,/gifCode,/,/actuator/**,/test/**,/apphtml/**,/scapp/**,/scimages/**,/merchant_wximge/**,/images22/**,/ckeditor/**,/upload/**,/swagger-resources/**,/webjars/**,/v2/**,/swagger-ui.html/**
    # 登录 url
    loginUrl: /login
    # 登录成功后跳转的 url
    successUrl: /index
    # 登出 url
    logoutUrl: /logout
    # 未授权跳转 url
    unauthorizedUrl: /403
  # 时间类型参数在前端页面的展示格式，默认格式为 yyyy-MM-dd HH:mm:ss
  timeFormat: yyyy-MM-dd HH:mm:ss
  # 是否开启 AOP 操作日志，默认开启
  openAopLog: true
  # 参数
  validateCode:
    # 宽度，默认 146px
    width: 160
    # 高度，默认 33px
    height: 50
    # 验证码字符个数，默认4个字符
    length: 2

